baseurl                 = "/"
DefaultContentLanguage  = "en"
title                   = "Gustv blog"
preserveTaxonomyNames   = false
paginate                = 3
disqusShortname         = "www"
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = [""]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]

  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  
  viewMorePostsLink     = "/blog/"
  
  readingTime           = false
  socialShare           = []

  [params.meta]
    description         = "Study hard"
    author              = "Gustv1126"
    favicon             = true
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Gustv blog"
    dynamicTitles       = false
    searchMenu          = false
    shareMenu           = false
    languageMenu        = false

  [params.intro]
    header                = "Gustv Blog"
    paragraph = "Study Coding and so on"
    rssIntro = false
    socialIntro = false
    hideWhenSingleColumn  = true
    alwaysOnHomepage      = true

    [params.intro.pic]
      src                 = "/img/logo1.png"
      shape               = "circle"
      width               = "100"
      alt                 = "icon-Gustv"

  [params.sidebar]
    about               = "Who is Gustv"
    postAmount          = 3
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  
    gitProvider         = "github"  # either "github" or "gitlab"
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = "" # Site Key
      encryptedKey      = ""

[menu]
  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/home/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Pictures"
    identifier        = "pictures"
    url               = "/pictures/"
    pre               = "<i class='fas fa-newspaper'></i>"
    weight            = 5

[Languages]
  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  github                = "Gustv1126"
  email                 = "example@mail.com"
